BEGIN { 
	print "/* generated by makeerror.awk from errorcodes */";
	print "#ifdef DEF_ERRMSG"
	print "char *errmsg[] = {"; 
}
/^ER/ {
	code = $1;
	codes[ci++] = code;
	e = substr($0, length(code)+1); 
	sub("[ \t]*","",e);
	printf("\t\"%s\",\n", e); 
}
END { 
	printf("\t\"%s\"\n", "unknown error");
	print "};"; 
	print "#else";
	print "typedef enum errorenum {";
	for (i = 0; i < ci; i++) {
		if (i == 0)
			printf("\t%s = 1,\n", codes[i]);
		else
			printf("\t%s,\n", codes[i]);
	}
	printf("\t%s\n", "ER_WTF");
	print "} error_t;"
	print "#endif";
}
