/*
 * cc2 - Second pass of ccc compiler
 * Code generation stub
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char *progname;

void
usage(char *complaint)
{
    if (complaint) {
        printf("%s\n", complaint);
    }
    printf("usage: %s [<options>] <ast_file>\n", progname);
    printf("  -o <output>    Output file (default: a.out)\n");
    exit(1);
}

int
main(int argc, char **argv)
{
    char *ast_file = NULL;
    char *output_file = "a.out";
    FILE *fp;
    char line[1024];
    int func_count = 0;
    int line_count = 0;

    progname = argv[0];
    argc--;
    argv++;

    /* Parse arguments */
    while (argc > 0) {
        if (strcmp(argv[0], "-o") == 0) {
            argc--;
            argv++;
            if (argc == 0) {
                usage("output file not specified");
            }
            output_file = argv[0];
            argc--;
            argv++;
        } else if (strcmp(argv[0], "-h") == 0 || strcmp(argv[0], "--help") == 0) {
            usage(NULL);
        } else if (argv[0][0] == '-') {
            printf("Unknown option: %s\n", argv[0]);
            usage(NULL);
        } else {
            /* AST input file */
            ast_file = argv[0];
            argc--;
            argv++;
        }
    }

    if (!ast_file) {
        usage("no AST input file specified");
    }

    printf("cc2: Reading AST from %s\n", ast_file);

    /* Open and read AST file */
    fp = fopen(ast_file, "r");
    if (!fp) {
        perror(ast_file);
        exit(1);
    }

    /* Count functions and lines in AST */
    while (fgets(line, sizeof(line), fp)) {
        line_count++;
        if (strncmp(line, "; Function:", 11) == 0) {
            func_count++;
            /* Print function name */
            printf("  Found function: %s", line + 12);
        }
    }
    fclose(fp);

    printf("cc2: Processed %d functions, %d lines of AST\n", func_count, line_count);
    printf("cc2: Code generation stub - would write to: %s\n", output_file);

    /* Create a placeholder output file */
    fp = fopen(output_file, "w");
    if (!fp) {
        perror(output_file);
        exit(1);
    }
    fprintf(fp, "#!/bin/sh\n");
    fprintf(fp, "# Placeholder executable generated by cc2 stub\n");
    fprintf(fp, "echo 'This is a stub executable from cc2'\n");
    fprintf(fp, "echo 'Generated from: %s'\n", ast_file);
    fprintf(fp, "echo 'Contains %d functions'\n", func_count);
    fclose(fp);

    /* Make output file executable */
    chmod(output_file, 0755);

    printf("cc2: Success - created stub executable: %s\n", output_file);
    return 0;
}
