/*
 * cc2 - Second pass of ccc compiler
 * Code generation stub
 */
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>

/* Forward declaration from util.c */
int fdprintf(int fd, const char *fmt, ...);

char *progname;

void
usage(char *complaint)
{
    if (complaint) {
        fdprintf(2, "%s\n", complaint);
    }
    fdprintf(2, "usage: %s [<options>] <ast_file>\n", progname);
    fdprintf(2, "  -o <output>    Output file (default: a.out)\n");
    exit(1);
}

int
main(int argc, char **argv)
{
    char *ast_file = NULL;
    char *output_file = "a.out";
    int in_fd, out_fd;
    char buf[4096];
    char line[1024];
    int func_count = 0;
    int line_count = 0;
    int n, i, line_len;
    char c;

    progname = argv[0];
    argc--;
    argv++;

    /* Parse arguments */
    while (argc > 0) {
        if (strcmp(argv[0], "-o") == 0) {
            argc--;
            argv++;
            if (argc == 0) {
                usage("output file not specified");
            }
            output_file = argv[0];
            argc--;
            argv++;
        } else if (strcmp(argv[0], "-h") == 0 || strcmp(argv[0], "--help") == 0) {
            usage(NULL);
        } else if (argv[0][0] == '-') {
            fdprintf(2, "Unknown option: %s\n", argv[0]);
            usage(NULL);
        } else {
            /* AST input file */
            ast_file = argv[0];
            argc--;
            argv++;
        }
    }

    if (!ast_file) {
        usage("no AST input file specified");
    }

    fdprintf(1, "cc2: Reading AST from %s\n", ast_file);

    /* Open and read AST file */
    in_fd = open(ast_file, O_RDONLY);
    if (in_fd < 0) {
        fdprintf(2, "cc2: cannot open %s\n", ast_file);
        exit(1);
    }

    /* Count functions and lines in AST */
    line_len = 0;
    while ((n = read(in_fd, buf, sizeof(buf))) > 0) {
        for (i = 0; i < n; i++) {
            c = buf[i];
            if (c == '\n') {
                line[line_len] = '\0';
                line_count++;
                if (strncmp(line, "; Function:", 11) == 0) {
                    func_count++;
                    /* Print function name */
                    fdprintf(1, "  Found function: %s\n", line + 12);
                }
                line_len = 0;
            } else if (line_len < sizeof(line) - 1) {
                line[line_len++] = c;
            }
        }
    }
    close(in_fd);

    fdprintf(1, "cc2: Processed %d functions, %d lines of AST\n", func_count, line_count);
    fdprintf(1, "cc2: Code generation stub - would write to: %s\n", output_file);

    /* Create a placeholder output file */
    out_fd = open(output_file, O_WRONLY | O_CREAT | O_TRUNC, 0755);
    if (out_fd < 0) {
        fdprintf(2, "cc2: cannot create %s\n", output_file);
        exit(1);
    }
    fdprintf(out_fd, "#!/bin/sh\n");
    fdprintf(out_fd, "# Placeholder executable generated by cc2 stub\n");
    fdprintf(out_fd, "echo 'This is a stub executable from cc2'\n");
    fdprintf(out_fd, "echo 'Generated from: %s'\n", ast_file);
    fdprintf(out_fd, "echo 'Contains %d functions'\n", func_count);
    close(out_fd);

    fdprintf(1, "cc2: Success - created stub executable: %s\n", output_file);
    return 0;
}
