/*
 * cc2.c - Main file for pass2 code generator
 *
 * Contains global state, symbol table, and main()
 * Other code is in: astio.c, emit.c, codegen.c, parseast.c, emitexpr.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>

#include "cc2.h"

/* Global state */
int infd;
int outfd;
unsigned char curchar;
int lineno = 1;
int patternOnly = 0;

/* Allocation counters (defined in parseast.c) */
#ifdef DEBUG
extern int exprAlloc;
extern int exprFree;
#endif

/* Register names indexed by R_* constants */
char *regnames[] = { 0, "b", "c", "bc", "ix", "de", "hl", "a", "iy",
                     "(ix)", "(iy)", "(ix%+d)", "(iy%+d)", "tos" };

/* Symbol table for locals/register vars */
struct sym locals[MAXLOCALS];
unsigned char nlocals;

/* Switch statement stack */
struct swctx swstack[MAXSWDEPTH];
unsigned char swdepth;

void
clearLocals(void)
{
    nlocals = 0;
}

void
addLocal(char *name, char type, char reg, char off)
{
    struct sym *s;
    if (nlocals < MAXLOCALS) {
        s = &locals[nlocals];
        strncpy(s->name, name, 13);
        s->name[13] = 0;
        s->type = type;
        s->reg = reg;
        s->off = off;
        nlocals++;
    }
}

struct sym *
findLocal(char *name)
{
    unsigned char i = nlocals;
    struct sym *s = locals;

    while (i--) {
        if (strcmp(s->name, name) == 0)
            return s;
        s++;
    }
    return 0;
}

/*
 * Main: cc2 [-p] input.ast [-o output.s]
 * Or legacy: cc2 input.ast temp2 output.s
 */
int
main(int argc, char **argv)
{
    char *infile = 0;
    char *outfile = 0;
    int i;

    for (i = 1; i < argc; i++) {
        if (argv[i][0] == '-') {
            switch (argv[i][1]) {
            case 'p':
                patternOnly = 1;
                break;
            case 'o':
                if (++i < argc)
                    outfile = argv[i];
                break;
            }
        } else if (!infile) {
            infile = argv[i];
        } else if (!outfile) {
            /* legacy: second positional is temp2 (ignored), third is output */
            if (i + 1 < argc)
                outfile = argv[++i];
        }
    }

    if (!infile || !outfile) {
        fprintf(stderr, "usage: cc2 [-p] input.ast -o output.s\n");
        return 1;
    }

    infd = open(infile, O_RDONLY);
    if (infd < 0) {
        perror(infile);
        return 1;
    }

    outfd = creat(outfile, 0644);
    if (outfd < 0) {
        perror(outfile);
        return 1;
    }

    advance();

    emit("; Generated by pass2");
    emit("");

    parseAst();

    close(infd);
    close(outfd);

#ifdef DEBUG
    fprintf(stderr, "exprs: %d/%d\n", exprAlloc, exprFree);
#endif

    return 0;
}

/*
 * vim: tabstop=4 shiftwidth=4 expandtab:
 */
