/*
 * newcc2.c - Main file for newpass2 code generator
 *
 * Contains global state, symbol table, and main()
 * Other code is in: astio.c, emit.c, codegen.c, parseast.c, emitexpr.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>

#include "cc2.h"

/* Global state */
int infd;
int outfd;
unsigned char curchar;
int lineno = 1;

/* Register names indexed by R_* constants */
char *regnames[] = { 0, "b", "c", "bc", "ix", "de", "hl", "a", "iy",
                     "(ix)", "(iy)", "(ix%+d)", "(iy%+d)", "tos" };

/* Symbol table for locals/register vars */
struct sym locals[MAXLOCALS];
unsigned char nlocals;

/* Switch statement stack */
struct swctx swstack[MAXSWDEPTH];
unsigned char swdepth;

void
clearLocals(void)
{
    nlocals = 0;
}

void
addLocal(char *name, char type, int reg, int off)
{
    struct sym *s;
    if (nlocals < MAXLOCALS) {
        s = &locals[nlocals];
        strncpy(s->name, name, 13);
        s->name[13] = 0;
        s->type = type;
        s->reg = reg;
        s->off = off;
        nlocals++;
    }
}

struct sym *
findLocal(char *name)
{
    unsigned char i = nlocals;
    struct sym *s = locals;

    while (i--) {
        if (strcmp(s->name, name) == 0)
            return s;
        s++;
    }
    return 0;
}

/*
 * Main
 */
int
main(int argc, char **argv)
{
    char *infile = 0;
    char *outfile = 0;

    argc--;
    argv++;

    while (argc > 0) {
        if (strcmp(argv[0], "-o") == 0) {
            argc--;
            argv++;
            if (argc > 0) {
                outfile = argv[0];
                argc--;
                argv++;
            }
        } else {
            infile = argv[0];
            argc--;
            argv++;
        }
    }

    if (!infile) {
        fprintf(stderr, "usage: cc2 [-o out] input.ast\n");
        return 1;
    }

    infd = open(infile, O_RDONLY);
    if (infd < 0) {
        perror(infile);
        return 1;
    }

    if (outfile) {
        outfd = open(outfile, O_WRONLY | O_CREAT | O_TRUNC, 0644);
        if (outfd < 0) {
            perror(outfile);
            return 1;
        }
    } else {
        outfd = 1;
    }

    advance();

    emit("; Generated by newpass2 (AST dump mode)");
    emit("");

    parseAst();

    close(infd);
    if (outfd != 1) close(outfd);

    return 0;
}

/*
 * vim: tabstop=4 shiftwidth=4 expandtab:
 */
